<?php


/**
 * This class adds structure of 'menuinfo' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 15 00:40:22 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MenuinfoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MenuinfoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(MenuinfoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(MenuinfoPeer::TABLE_NAME);
		$tMap->setPhpName('Menuinfo');
		$tMap->setClassname('Menuinfo');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('MENUNAME', 'Menuname', 'VARCHAR', true, 50);

		$tMap->addColumn('MENU_LINK', 'MenuLink', 'VARCHAR', true, 100);

		$tMap->addColumn('PARENT_ID', 'ParentId', 'INTEGER', true, null);

		$tMap->addForeignKey('SHOPINFO_ID', 'ShopinfoId', 'INTEGER', 'shopinfo', 'ID', true, null);

	} // doBuild()

} // MenuinfoMapBuilder
