<?php


/**
 * This class adds structure of 'shoppage' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Aug 15 00:40:22 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ShoppageMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ShoppageMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ShoppagePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ShoppagePeer::TABLE_NAME);
		$tMap->setPhpName('Shoppage');
		$tMap->setClassname('Shoppage');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('PAGE_TITLE', 'PageTitle', 'VARCHAR', true, 50);

		$tMap->addColumn('PAGE_NUMBER', 'PageNumber', 'VARCHAR', true, 20);

		$tMap->addColumn('PAGE_CONTENT', 'PageContent', 'LONGVARCHAR', true, null);

		$tMap->addForeignKey('SHOPINFO_ID', 'ShopinfoId', 'INTEGER', 'shopinfo', 'ID', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('IS_MAINPAGE', 'IsMainpage', 'TINYINT', true, null);

	} // doBuild()

} // ShoppageMapBuilder
