<?php

/**
 * Base class that represents a row from the 'shopinfo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Aug 18 19:18:25 2013
 *
 * @package    lib.model.om
 */
abstract class BaseShopinfo extends BaseObject  implements Persistent {


  const PEER = 'ShopinfoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ShopinfoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the f_name field.
	 * Note: this column has a database default value of: 'null'
	 * @var        string
	 */
	protected $f_name;

	/**
	 * The value for the f_password field.
	 * Note: this column has a database default value of: 'null'
	 * @var        string
	 */
	protected $f_password;

	/**
	 * The value for the f_number field.
	 * Note: this column has a database default value of: 'null'
	 * @var        string
	 */
	protected $f_number;

	/**
	 * The value for the f_mobile field.
	 * Note: this column has a database default value of: 'null'
	 * @var        string
	 */
	protected $f_mobile;

	/**
	 * The value for the f_address field.
	 * Note: this column has a database default value of: 'null'
	 * @var        string
	 */
	protected $f_address;

	/**
	 * The value for the f_fid field.
	 * Note: this column has a database default value of: 'null'
	 * @var        string
	 */
	protected $f_fid;

	/**
	 * @var        array Menuinfo[] Collection to store aggregation of Menuinfo objects.
	 */
	protected $collMenuinfos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMenuinfos.
	 */
	private $lastMenuinfoCriteria = null;

	/**
	 * @var        array Shoppage[] Collection to store aggregation of Shoppage objects.
	 */
	protected $collShoppages;

	/**
	 * @var        Criteria The criteria used to select the current contents of collShoppages.
	 */
	private $lastShoppageCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseShopinfo object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->f_name = 'null';
		$this->f_password = 'null';
		$this->f_number = 'null';
		$this->f_mobile = 'null';
		$this->f_address = 'null';
		$this->f_fid = 'null';
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [f_name] column value.
	 * 
	 * @return     string
	 */
	public function getFName()
	{
		return $this->f_name;
	}

	/**
	 * Get the [f_password] column value.
	 * 
	 * @return     string
	 */
	public function getFPassword()
	{
		return $this->f_password;
	}

	/**
	 * Get the [f_number] column value.
	 * 
	 * @return     string
	 */
	public function getFNumber()
	{
		return $this->f_number;
	}

	/**
	 * Get the [f_mobile] column value.
	 * 
	 * @return     string
	 */
	public function getFMobile()
	{
		return $this->f_mobile;
	}

	/**
	 * Get the [f_address] column value.
	 * 
	 * @return     string
	 */
	public function getFAddress()
	{
		return $this->f_address;
	}

	/**
	 * Get the [f_fid] column value.
	 * 
	 * @return     string
	 */
	public function getFFid()
	{
		return $this->f_fid;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ShopinfoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [f_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setFName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->f_name !== $v || $v === 'null') {
			$this->f_name = $v;
			$this->modifiedColumns[] = ShopinfoPeer::F_NAME;
		}

		return $this;
	} // setFName()

	/**
	 * Set the value of [f_password] column.
	 * 
	 * @param      string $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setFPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->f_password !== $v || $v === 'null') {
			$this->f_password = $v;
			$this->modifiedColumns[] = ShopinfoPeer::F_PASSWORD;
		}

		return $this;
	} // setFPassword()

	/**
	 * Set the value of [f_number] column.
	 * 
	 * @param      string $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setFNumber($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->f_number !== $v || $v === 'null') {
			$this->f_number = $v;
			$this->modifiedColumns[] = ShopinfoPeer::F_NUMBER;
		}

		return $this;
	} // setFNumber()

	/**
	 * Set the value of [f_mobile] column.
	 * 
	 * @param      string $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setFMobile($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->f_mobile !== $v || $v === 'null') {
			$this->f_mobile = $v;
			$this->modifiedColumns[] = ShopinfoPeer::F_MOBILE;
		}

		return $this;
	} // setFMobile()

	/**
	 * Set the value of [f_address] column.
	 * 
	 * @param      string $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setFAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->f_address !== $v || $v === 'null') {
			$this->f_address = $v;
			$this->modifiedColumns[] = ShopinfoPeer::F_ADDRESS;
		}

		return $this;
	} // setFAddress()

	/**
	 * Set the value of [f_fid] column.
	 * 
	 * @param      string $v new value
	 * @return     Shopinfo The current object (for fluent API support)
	 */
	public function setFFid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->f_fid !== $v || $v === 'null') {
			$this->f_fid = $v;
			$this->modifiedColumns[] = ShopinfoPeer::F_FID;
		}

		return $this;
	} // setFFid()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(ShopinfoPeer::F_NAME,ShopinfoPeer::F_PASSWORD,ShopinfoPeer::F_NUMBER,ShopinfoPeer::F_MOBILE,ShopinfoPeer::F_ADDRESS,ShopinfoPeer::F_FID))) {
				return false;
			}

			if ($this->f_name !== 'null') {
				return false;
			}

			if ($this->f_password !== 'null') {
				return false;
			}

			if ($this->f_number !== 'null') {
				return false;
			}

			if ($this->f_mobile !== 'null') {
				return false;
			}

			if ($this->f_address !== 'null') {
				return false;
			}

			if ($this->f_fid !== 'null') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->f_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->f_password = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->f_number = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->f_mobile = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->f_address = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->f_fid = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = ShopinfoPeer::NUM_COLUMNS - ShopinfoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Shopinfo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShopinfoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ShopinfoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collMenuinfos = null;
			$this->lastMenuinfoCriteria = null;

			$this->collShoppages = null;
			$this->lastShoppageCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseShopinfo:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShopinfoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ShopinfoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseShopinfo:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseShopinfo:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ShopinfoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseShopinfo:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ShopinfoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ShopinfoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ShopinfoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ShopinfoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collMenuinfos !== null) {
				foreach ($this->collMenuinfos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collShoppages !== null) {
				foreach ($this->collShoppages as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ShopinfoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collMenuinfos !== null) {
					foreach ($this->collMenuinfos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collShoppages !== null) {
					foreach ($this->collShoppages as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ShopinfoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getFName();
				break;
			case 2:
				return $this->getFPassword();
				break;
			case 3:
				return $this->getFNumber();
				break;
			case 4:
				return $this->getFMobile();
				break;
			case 5:
				return $this->getFAddress();
				break;
			case 6:
				return $this->getFFid();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ShopinfoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getFName(),
			$keys[2] => $this->getFPassword(),
			$keys[3] => $this->getFNumber(),
			$keys[4] => $this->getFMobile(),
			$keys[5] => $this->getFAddress(),
			$keys[6] => $this->getFFid(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ShopinfoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setFName($value);
				break;
			case 2:
				$this->setFPassword($value);
				break;
			case 3:
				$this->setFNumber($value);
				break;
			case 4:
				$this->setFMobile($value);
				break;
			case 5:
				$this->setFAddress($value);
				break;
			case 6:
				$this->setFFid($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ShopinfoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFPassword($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFNumber($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFMobile($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFAddress($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFFid($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ShopinfoPeer::DATABASE_NAME);

		if ($this->isColumnModified(ShopinfoPeer::ID)) $criteria->add(ShopinfoPeer::ID, $this->id);
		if ($this->isColumnModified(ShopinfoPeer::F_NAME)) $criteria->add(ShopinfoPeer::F_NAME, $this->f_name);
		if ($this->isColumnModified(ShopinfoPeer::F_PASSWORD)) $criteria->add(ShopinfoPeer::F_PASSWORD, $this->f_password);
		if ($this->isColumnModified(ShopinfoPeer::F_NUMBER)) $criteria->add(ShopinfoPeer::F_NUMBER, $this->f_number);
		if ($this->isColumnModified(ShopinfoPeer::F_MOBILE)) $criteria->add(ShopinfoPeer::F_MOBILE, $this->f_mobile);
		if ($this->isColumnModified(ShopinfoPeer::F_ADDRESS)) $criteria->add(ShopinfoPeer::F_ADDRESS, $this->f_address);
		if ($this->isColumnModified(ShopinfoPeer::F_FID)) $criteria->add(ShopinfoPeer::F_FID, $this->f_fid);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ShopinfoPeer::DATABASE_NAME);

		$criteria->add(ShopinfoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Shopinfo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFName($this->f_name);

		$copyObj->setFPassword($this->f_password);

		$copyObj->setFNumber($this->f_number);

		$copyObj->setFMobile($this->f_mobile);

		$copyObj->setFAddress($this->f_address);

		$copyObj->setFFid($this->f_fid);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getMenuinfos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMenuinfo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getShoppages() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addShoppage($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Shopinfo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ShopinfoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ShopinfoPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collMenuinfos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMenuinfos()
	 */
	public function clearMenuinfos()
	{
		$this->collMenuinfos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMenuinfos collection (array).
	 *
	 * By default this just sets the collMenuinfos collection to an empty array (like clearcollMenuinfos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMenuinfos()
	{
		$this->collMenuinfos = array();
	}

	/**
	 * Gets an array of Menuinfo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Shopinfo has previously been saved, it will retrieve
	 * related Menuinfos from storage. If this Shopinfo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Menuinfo[]
	 * @throws     PropelException
	 */
	public function getMenuinfos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ShopinfoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMenuinfos === null) {
			if ($this->isNew()) {
			   $this->collMenuinfos = array();
			} else {

				$criteria->add(MenuinfoPeer::SHOPINFO_ID, $this->id);

				MenuinfoPeer::addSelectColumns($criteria);
				$this->collMenuinfos = MenuinfoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MenuinfoPeer::SHOPINFO_ID, $this->id);

				MenuinfoPeer::addSelectColumns($criteria);
				if (!isset($this->lastMenuinfoCriteria) || !$this->lastMenuinfoCriteria->equals($criteria)) {
					$this->collMenuinfos = MenuinfoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMenuinfoCriteria = $criteria;
		return $this->collMenuinfos;
	}

	/**
	 * Returns the number of related Menuinfo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Menuinfo objects.
	 * @throws     PropelException
	 */
	public function countMenuinfos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ShopinfoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMenuinfos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MenuinfoPeer::SHOPINFO_ID, $this->id);

				$count = MenuinfoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MenuinfoPeer::SHOPINFO_ID, $this->id);

				if (!isset($this->lastMenuinfoCriteria) || !$this->lastMenuinfoCriteria->equals($criteria)) {
					$count = MenuinfoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMenuinfos);
				}
			} else {
				$count = count($this->collMenuinfos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Menuinfo object to this object
	 * through the Menuinfo foreign key attribute.
	 *
	 * @param      Menuinfo $l Menuinfo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMenuinfo(Menuinfo $l)
	{
		if ($this->collMenuinfos === null) {
			$this->initMenuinfos();
		}
		if (!in_array($l, $this->collMenuinfos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMenuinfos, $l);
			$l->setShopinfo($this);
		}
	}

	/**
	 * Clears out the collShoppages collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addShoppages()
	 */
	public function clearShoppages()
	{
		$this->collShoppages = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collShoppages collection (array).
	 *
	 * By default this just sets the collShoppages collection to an empty array (like clearcollShoppages());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initShoppages()
	{
		$this->collShoppages = array();
	}

	/**
	 * Gets an array of Shoppage objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Shopinfo has previously been saved, it will retrieve
	 * related Shoppages from storage. If this Shopinfo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Shoppage[]
	 * @throws     PropelException
	 */
	public function getShoppages($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ShopinfoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collShoppages === null) {
			if ($this->isNew()) {
			   $this->collShoppages = array();
			} else {

				$criteria->add(ShoppagePeer::SHOPINFO_ID, $this->id);

				ShoppagePeer::addSelectColumns($criteria);
				$this->collShoppages = ShoppagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ShoppagePeer::SHOPINFO_ID, $this->id);

				ShoppagePeer::addSelectColumns($criteria);
				if (!isset($this->lastShoppageCriteria) || !$this->lastShoppageCriteria->equals($criteria)) {
					$this->collShoppages = ShoppagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastShoppageCriteria = $criteria;
		return $this->collShoppages;
	}

	/**
	 * Returns the number of related Shoppage objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Shoppage objects.
	 * @throws     PropelException
	 */
	public function countShoppages(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ShopinfoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collShoppages === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ShoppagePeer::SHOPINFO_ID, $this->id);

				$count = ShoppagePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ShoppagePeer::SHOPINFO_ID, $this->id);

				if (!isset($this->lastShoppageCriteria) || !$this->lastShoppageCriteria->equals($criteria)) {
					$count = ShoppagePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collShoppages);
				}
			} else {
				$count = count($this->collShoppages);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Shoppage object to this object
	 * through the Shoppage foreign key attribute.
	 *
	 * @param      Shoppage $l Shoppage
	 * @return     void
	 * @throws     PropelException
	 */
	public function addShoppage(Shoppage $l)
	{
		if ($this->collShoppages === null) {
			$this->initShoppages();
		}
		if (!in_array($l, $this->collShoppages, true)) { // only add it if the **same** object is not already associated
			array_push($this->collShoppages, $l);
			$l->setShopinfo($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collMenuinfos) {
				foreach ((array) $this->collMenuinfos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collShoppages) {
				foreach ((array) $this->collShoppages as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collMenuinfos = null;
		$this->collShoppages = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseShopinfo:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseShopinfo::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseShopinfo
