shopPage:
  url: /page/:shopId/:pageId
  param:  {module: guestPage, action: index }

home:
  url: /
  param: { module: home, action: index }

login:
  url: /account/login
  param: { module: account, action: login }
# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
