menuManage:
  url: /menu/index
  param: {module: menu, action: index }

pageManage:
  url: /page/index
  param: {module: page, action: index }
#guest shoppages
shopHome:
  url: /page/:shopId
  param: {module: shopHome, action: index }

shopPage:
  url: /page/:shopId/:pageId
  param:  {module: guestPage, action: index }

#home
home:
  url: /index
  param: { module: home, action: index }

login:
  url: /account/login
  param: { module: account, action: login }
# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
