<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2013/08/14 20:00:53
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // sfPropelPlugin_module_libs

  // propel
  'PropelException' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/PropelException.php',
  'PropelDateTime' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelDateTime.php',
  'NodePeer' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/NodePeer.php',
  'PropelColumnTypes' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelColumnTypes.php',
  'PropelPDO' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelPDO.php',
  'Criteria' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'CriterionIterator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'Criterion' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'Join' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'PropelPager' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelPager.php',
  'DebugPDOStatement' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/DebugPDOStatement.php',
  'BasePeer' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/BasePeer.php',
  'DebugPDO' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/DebugPDO.php',
  'MojaviLogAdapter' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/logger/MojaviLogAdapter.php',
  'BasicLogger' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/logger/BasicLogger.php',
  'BaseObject' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/BaseObject.php',
  'NodeObject' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/NodeObject.php',
  'NestedSetRecursiveIterator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/NestedSetRecursiveIterator.php',
  'Persistent' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/Persistent.php',
  'PreOrderNodeIterator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/PreOrderNodeIterator.php',
  'TableMap' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/TableMap.php',
  'MapBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/MapBuilder.php',
  'ValidatorMap' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/ValidatorMap.php',
  'ColumnMap' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/ColumnMap.php',
  'DatabaseMap' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/DatabaseMap.php',
  'Propel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/Propel.php',
  'MinValueValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MinValueValidator.php',
  'UniqueValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/UniqueValidator.php',
  'RequiredValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/RequiredValidator.php',
  'MaxLengthValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MaxLengthValidator.php',
  'MinLengthValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MinLengthValidator.php',
  'MatchValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MatchValidator.php',
  'BasicValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/BasicValidator.php',
  'ValidationFailed' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/ValidationFailed.php',
  'TypeValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/TypeValidator.php',
  'NotMatchValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/NotMatchValidator.php',
  'ValidValuesValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/ValidValuesValidator.php',
  'MaxValueValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MaxValueValidator.php',
  'DBMSSQL' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBMSSQL.php',
  'DBAdapter' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBAdapter.php',
  'DBSQLite' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBSQLite.php',
  'DBNone' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBNone.php',
  'DBMySQL' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBMySQL.php',
  'DBOracle' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBOracle.php',
  'DBPostgres' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBPostgres.php',

  // propel_class
  'Propel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelAutoload.php',

  // sfPropelPlugin_lib
  'sfWidgetFormPropelChoice' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfWidgetFormPropelSelect' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelSelect.class.php',
  'sfWidgetFormPropelSelectMany' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelSelectMany.class.php',
  'sfWidgetFormPropelChoiceMany' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoiceMany.class.php',
  'sfWebDebugPanelPropel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfTesterPropel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfPropelBuildAllLoadTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfPropelBuildSqlTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfPropelInitAdminTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInitAdminTask.class.php',
  'sfPropelGenerateAdminTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfPropelGenerateModuleForRouteTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfPropelGraphvizTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfPropelDumpDataTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDumpDataTask.class.php',
  'sfPropelGenerateModuleTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfPropelBaseTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfPropelBuildFiltersTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfPropelSchemaToYmlTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfPropelBuildFormsTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfPhing' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfPropelLoadDataTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelLoadDataTask.class.php',
  'sfPhingListener' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfPropelBuildAllTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfPropelSchemaToXmlTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfPropelBuildModelTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfPropelInsertSqlTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfPropelBuildSchemaTask' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfPropelLogger' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'sfPropelDatabase' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfPropelDataRetriever' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDataRetriever.class.php',
  'sfFormPropel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfFormFilterPropel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfPropelRoute' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfPropelRouteCollection' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfPropelDatabaseSchema' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfPropelData' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfPropel' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfPropelPager' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfPropelBehavior' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfPropelManyToMany' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfMixer' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfValidatorPropelChoice' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfValidatorPropelChoiceMany' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoiceMany.class.php',
  'sfPropelUniqueValidator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfPropelUniqueValidator.class.php',
  'sfValidatorPropelUnique' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'SfExtensionObjectBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfExtensionObjectBuilder.php',
  'SfObjectBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfObjectBuilder.php',
  'SfMultiExtendObjectBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfMultiExtendObjectBuilder.php',
  'SfPeerBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfPeerBuilder.php',
  'SfNestedSetBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfNestedSetBuilder.php',
  'SfExtensionPeerBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfExtensionPeerBuilder.php',
  'SfMapBuilderBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfMapBuilderBuilder.php',
  'SfNestedSetPeerBuilder' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfNestedSetPeerBuilder.php',
  'sfPropelCrudGenerator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelCrudGenerator.class.php',
  'sfPropelFormGenerator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfPropelAdminGenerator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelAdminGenerator.class.php',
  'sfPropelFormFilterGenerator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfPropelGenerator' => '/home/tony/city/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',

  // project

  // project_model

  // application
  'myUser' => '/home/tony/city/apps/frontend/lib/myUser.class.php',

  // modules
);
