<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/14 20:00:53

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=health;host=localhost',
  'username' => 'root',
  'password' => 111111,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
